### ISSUE TITLE
running Auto_ViML with python interpreter throws an ipython exception.

### ISSUE THREAD

**Issue by manugarri** [AutoViML/Auto_ViML#12]
Im testing Auto_Viml as one of automl containers in my pipeline. However, running Auto_Viml function from a script  (or importing it from standard python REPL) throws the following exception:

```
    from autoviml.Auto_ViML import Auto_ViML
  File "/usr/local/lib/python3.7/site-packages/autoviml/Auto_ViML.py", line 29, in <module>
    get_ipython().magic(u'matplotlib inline')
NameError: name 'get_ipython' is not defined
```

This can be fixed by either using a jupyter notebook (which i imagine is the only thing tested so far) or using `ipython` instead of `python`. This is ok for toy examples but in production systems python is the default executable. 

Would make sense to make ipython magic not fail.

I am using `autoviml==0.1.651`

**Comment by AutoViML** [comment]
Hi:
Thanks for trying out Auto_ViML. I have not been too keen on removing get_ipython since a lot of the benefits of Auto_ViML are for trying out different models and techniques to find what works best on your data set. This kind of experimentation works well only a Jupyter Notebook. Hence I don't find the need to remove get_ipython yet. I might make a version available once I get the pipeline working. Until then, this is going to be strictly for those data scientists who want to build a challenger model using Jupyter Notebooks. Hope this clears any misunderstandings.
thanks

**Comment by manugarri** [comment]
Got it, i think i will stop using the (very promising) project until then, in my case there is no point in testing models that i cant use afterwards.
