### ISSUE TITLE
How do use save model?

### ISSUE THREAD

**Issue by miggytrinidad** [AutoViML/Auto_ViML#27]
How do you use the saved model? How do I get the transformations during the training for predictions later on?

**Comment by AutoViML** [comment]
Hi @miggytrinidad : thanks for using AutoViML and for your feedback 👍 

Currently the saved model does not contain the transforms needed for predictions later. The reason is that I created AutoViML as a tool for teaching folks to build their own model based on learning how AutoViML builds a fine performing model. The goal was never to compete with AutoML products but to be the best "challenger" model that will challenge you to build a better model.

Hope this explanation helps,
Ram
