### ISSUE TITLE
Integration with sklearn-evaluation

### ISSUE THREAD

**Issue by idomic** [AutoViML/Auto_ViML#29]
I think adding an integration/tutorial and the right documentation of the [framework](https://github.com/ploomber/sklearn-evaluation) can go a long way.

Usually, when using Auto_ViML you'd get the final model, and then you'll check performance and results.
This will allow an easier mechanism for the users to solve the second part of it.

**Comment by AutoViML** [comment]
@idomic 
Thanks for trying out Auto_ViML 👍 

I like this idea but I don't have the time to integrate it. If you would like to make a copy of this repo and make changes and submit it back, I'd be happy to cite you as a contributor with a Linkedin Post.

Please let me know.
Thanks
Auto Vimal

**Comment by idomic** [comment]
@AutoViML thanks, will start working on it!

Are there docs we can put it in besides the `readme.md`?
What I can do (unless you have a better candidate tutorial) is taking the readme example, with some sample dataset, and once done training evaluating the model, features and generate a classification report.

**Comment by AutoViML** [comment]
@idomic 

Thank you for taking on this task 👍 

I would suggest putting it in the `readme.md` file at the bottom as a new update.

You can modify this example notebook and add sklearn evaluation toward the end.

[Titanic Example](https://github.com/AutoViML/Auto_ViML/blob/master/Example%20Notebook/Auto_ViML_Demo.ipynb)

You can download the titanic dataset from Kaggle.

Hope this helps!
Auto Vimal

**Comment by idomic** [comment]
I've started editting the code in `AutoViML.py` as a starter.
I tried running the `Auto_ViML_Demo.ipynb`, it errors out in the first cell about:

```
 #### If Boosting_Flag = True => XGBoost, Fase=>ExtraTrees, None=>Linear Model
----> 2 m, feats, trainm, testm = Auto_ViML(train, target, test, sample_submission,
      3                                     scoring_parameter=scoring_parameter,
      4                                     hyper_param='GS',feature_reduction=True,
      5                                      Boosting_Flag=True,Binning_Flag=False,
      6                                     Add_Poly=0, Stacking_Flag=False,                                    
      7                                     Imbalanced_Flag=False, 
      8                                     verbose=1)

TypeError: cannot unpack non-iterable NoneType object
```

This is even before I changed any code to use sklearn-evaluation instead of matplotlib

Any thoughts?

(importing passes fine: `from autoviml.Auto_ViML import Auto_ViML`)

**Comment by AutoViML** [comment]
@idomic 
sorry about that 👎 

You need to change the datapath in that notebook to this since it seems like the titanic file there might be broken.
`datapath = 'https://github.com/datasciencedojo/datasets/raw/master/'`

In addition, if you are running this on Colab, you need to change the runtime type to "GPU" hardware accelerator. Otherwise, the XGBoost version they have seems to error with AutoViML. That's what I found. 

Hope this helps,
Auto Vimal

**Comment by idomic** [comment]
No worries!
Do I have to have GPUs? I was trying to get it working locally on my mac. I think as part of this model there are some local GPUs, but might be easier on Colab if that's a hard requirement.

**Comment by AutoViML** [comment]
AutoVIML has worked for 1000's of users. I am not sure whether the XGBoost for CPU vs. GPU has changed and that's why we are hitting this error. I used a Colab since I thought that is what you were using. If you are using a Mac, just make sure that the GPU is "available" as an accelerator in the Jupyter Notebook that you are running since AutoVIML detects a GPU and expects it to be added to the Notebook when it is detected. You can even try it on a Kaggle Notebook or in a Colab as I suggested as long as GPU is turned on.
