### ISSUE TITLE
SHAP Plots

### ISSUE THREAD

**Issue by sparvaneh** [AutoViML/Auto_ViML#35]
I am getting "Could not plot SHAP values since SHAP is not installed or could not import SHAP in this machine" message for creating XGBoost model. Which version of SHAP is compatible with AutoVIML?

**Comment by AutoViML** [comment]
I am not sure what version I used - please try the latest version of SHAP - if not try a version about a year ago.Sorry couldn't remember.Auto Vimal

    On Monday, September 25, 2023 at 07:12:30 PM EDT, Saman ***@***.***> wrote:  
 
 


I am getting "Could not plot SHAP values since SHAP is not installed or could not import SHAP in this machine" message for creating XGBoost model. Which version of SHAP is compatible with AutoVIML?
