### ISSUE TITLE
How are you handling preprocessing steps during prediction?

### ISSUE THREAD

**Issue by deneshkumar** [AutoViML/Auto_ViML#4]
Hi @rsesha 

Currently Auto_ViML function is returning best model (XGB), features (Array), train metrics and  test metrics. But how you suggesting to handling the preprocessing in the prediction dataset?

For Example, if you are applying LabelEncoding on a column inside the Auto_ViML function during training

**Comment by rsesha** [comment]
Denesh
that will come in future versions. I have some code already ready. I just
need to find time to integrate it and test.
In the meantime, if you want to test the latest version, please do:

pip3 install --upgrade --force-reinstall --no-deps autoviml

This will take care of some bugs which crept in when I made the
CatBoost upgrade. It has really messed up my code a bit.

Ram

**Comment by AutoViML** [comment]
Actually this might work better for upgrading autoviml...
pip3 install --upgrade --ignore-installed  --no-deps autoviml
Ram

**Comment by deneshkumar** [comment]
Thanks for the quick response @rsesha 

I understand this has great exciting ways to go. I would like to contribute to restructuring this code, feel free to pass on if you have specific coding task to be done. I will do it and raise pull request.

**Comment by rsesha** [comment]
Denesh:
That would be awesome. I will ask you to start doing a CODE REVIEW with 2
goals in mind:
1. Make minimal suggestions for change
2. If you suggest, it can be to Clean up dead variables or speed up using
map, apply etc instead of "For" loop
Once that is done, I will ask you for more code changes. I expect this to
be a long process but if you are willing to work with it over time, I am
sure it can very rewarding.
You can also send me emails via the email address prvided on my GitHub.
Ram
